jetstream {
  store_dir: "/data"
}

accounts {
  TEST_SERVICE {
    jetstream {
      max_mem: 500Mi   # メモリ使用量の上限
      max_file: 5G  # ディスク使用量の上限
    }
    users: [
      { user: "user", password: "password" }
    ]
  }
}
