// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -package=interfaces -destination=../mock/interfaces/service.go
//

// Package interfaces is a generated GoMock package.
package interfaces

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/n-creativesystem/outbox-worker/pkg/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// FindResources mocks base method.
func (m *MockPublisher) FindResources(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResources", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindResources indicates an expected call of FindResources.
func (mr *MockPublisherMockRecorder) FindResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResources", reflect.TypeOf((*MockPublisher)(nil).FindResources), ctx)
}

// Publish mocks base method.
func (m *MockPublisher) Publish(ctx context.Context, outbox interfaces.Outbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, outbox)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(ctx, outbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), ctx, outbox)
}

// RefetchResources mocks base method.
func (m *MockPublisher) RefetchResources(ctx context.Context) chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefetchResources", ctx)
	ret0, _ := ret[0].(chan error)
	return ret0
}

// RefetchResources indicates an expected call of RefetchResources.
func (mr *MockPublisherMockRecorder) RefetchResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefetchResources", reflect.TypeOf((*MockPublisher)(nil).RefetchResources), ctx)
}

// MockBackendPublisher is a mock of BackendPublisher interface.
type MockBackendPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockBackendPublisherMockRecorder
	isgomock struct{}
}

// MockBackendPublisherMockRecorder is the mock recorder for MockBackendPublisher.
type MockBackendPublisherMockRecorder struct {
	mock *MockBackendPublisher
}

// NewMockBackendPublisher creates a new mock instance.
func NewMockBackendPublisher(ctrl *gomock.Controller) *MockBackendPublisher {
	mock := &MockBackendPublisher{ctrl: ctrl}
	mock.recorder = &MockBackendPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendPublisher) EXPECT() *MockBackendPublisherMockRecorder {
	return m.recorder
}

// FindResources mocks base method.
func (m *MockBackendPublisher) FindResources(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResources", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindResources indicates an expected call of FindResources.
func (mr *MockBackendPublisherMockRecorder) FindResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResources", reflect.TypeOf((*MockBackendPublisher)(nil).FindResources), ctx)
}

// Publish mocks base method.
func (m *MockBackendPublisher) Publish(ctx context.Context, outbox interfaces.Outbox) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, outbox)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockBackendPublisherMockRecorder) Publish(ctx, outbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBackendPublisher)(nil).Publish), ctx, outbox)
}
