// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/n-creativesystem/outbox-worker/pkg/interfaces"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// FindResources mocks base method.
func (m *MockPublisher) FindResources(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResources", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindResources indicates an expected call of FindResources.
func (mr *MockPublisherMockRecorder) FindResources(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResources", reflect.TypeOf((*MockPublisher)(nil).FindResources), ctx)
}

// PublishOutbox mocks base method.
func (m *MockPublisher) PublishOutbox(ctx context.Context, outbox interfaces.Outbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOutbox", ctx, outbox)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOutbox indicates an expected call of PublishOutbox.
func (mr *MockPublisherMockRecorder) PublishOutbox(ctx, outbox interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOutbox", reflect.TypeOf((*MockPublisher)(nil).PublishOutbox), ctx, outbox)
}

// RefetchResources mocks base method.
func (m *MockPublisher) RefetchResources(ctx context.Context) chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefetchResources", ctx)
	ret0, _ := ret[0].(chan error)
	return ret0
}

// RefetchResources indicates an expected call of RefetchResources.
func (mr *MockPublisherMockRecorder) RefetchResources(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefetchResources", reflect.TypeOf((*MockPublisher)(nil).RefetchResources), ctx)
}

// MockBackendPublisher is a mock of BackendPublisher interface.
type MockBackendPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockBackendPublisherMockRecorder
}

// MockBackendPublisherMockRecorder is the mock recorder for MockBackendPublisher.
type MockBackendPublisherMockRecorder struct {
	mock *MockBackendPublisher
}

// NewMockBackendPublisher creates a new mock instance.
func NewMockBackendPublisher(ctrl *gomock.Controller) *MockBackendPublisher {
	mock := &MockBackendPublisher{ctrl: ctrl}
	mock.recorder = &MockBackendPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendPublisher) EXPECT() *MockBackendPublisherMockRecorder {
	return m.recorder
}

// FindBackendResources mocks base method.
func (m *MockBackendPublisher) FindBackendResources(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBackendResources", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindBackendResources indicates an expected call of FindBackendResources.
func (mr *MockBackendPublisherMockRecorder) FindBackendResources(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBackendResources", reflect.TypeOf((*MockBackendPublisher)(nil).FindBackendResources), ctx)
}

// PublishOutbox mocks base method.
func (m *MockBackendPublisher) PublishOutbox(ctx context.Context, outbox interfaces.Outbox) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOutbox", ctx, outbox)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishOutbox indicates an expected call of PublishOutbox.
func (mr *MockBackendPublisherMockRecorder) PublishOutbox(ctx, outbox interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOutbox", reflect.TypeOf((*MockBackendPublisher)(nil).PublishOutbox), ctx, outbox)
}
